### ISSUE TITLE
The Dialog Always Defaults To Steam Game 271590 (Grand Theft Auto V)

### ISSUE THREAD

**Issue by ShandyAndy** [Gaffi/SG-WL-Inventory#4]
Each time I click on the "Check game ownership" button '271590' is already entered in the text box

Ideally I'd say it needs to be clear?

**Comment by Gaffi** [comment]
Not sure how I feel about this one. Generally, always defaulting is maybe not super ideal. However, for first-time or infrequent users, I wanted to have something there as a guide for the input format (i.e. not the game name or full http:// address, since there are other resources on the internet that will properly parse that. Maybe I'll just plug in a parsing bit to allow for multiple input formats.

**Comment by ShandyAndy** [comment]
Or possibly display the dialog box with the ID already highlighted so pasting over it or pressing delete key once removes it?

**Comment by Gaffi** [comment]
Not sure where the disconnect between our setups is, but mine does highlight the default value automatically. i.e. I can click the button, the prompt comes up, and I immediately paste and it works fine. I believe you! :) I'm just not sure how to guarantee it works that way for you when it already works that way for me.

**Comment by ShandyAndy** [comment]
My bad, you are absolutely right :)

**Comment by Gaffi** [comment]
No worries. Thanks for the attention to detail! I'd like to not have even those little things lingering.
